export default {
  LOAD_PRODUCT: 'LOAD_PRODUCT',
  LOAD_PRODUCT_SUCCESS: 'LOAD_PRODUCT_SUCCESS',
  LOAD_PRODUCT_ERROR: 'LOAD_PRODUCT_ERROR',
  ADD_TO_CART: 'ADD_TO_CART',
  ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
  ADD_TO_CART_ERROR: 'ADD_TO_CART_ERROR'
};
